// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "TOTPRegister.BACK": "Back",
    "TOTPRegister.HOW_TO_USE": "How to use authenticator app.",
    "TOTPRegister.INTRO": "Verification codes are created by an app on your phone. ",
    "TOTPRegister.MANUAL": "Enter manually the following code into authentication app:",
    "TOTPRegister.NEXT": "Next",
    "TOTPRegister.OR": "Or",
    "TOTPVerify.ENTER_CODE": "Enter {length}-digit code",
    "TOTPVerify.HOW_TO_USE": "How to use authenticator app.",
    "TOTPVerify.NEXT": "Next",
    "TOTPVerify.VERIFY": "Use verification code from your authenticator app. "
});
}