// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "TOTPRegister.BACK": "Antaŭa",
    "TOTPRegister.HOW_TO_USE": "Kiel uzi aŭtentigan aplikaĵon.",
    "TOTPRegister.INTRO": "Kontrolajn kodojn kreas aplikaĵo en via telefono.",
    "TOTPRegister.MANUAL": "Mane enigu la jenan kodon en la atentigan aplikaĵon.",
    "TOTPRegister.NEXT": "Sekva",
    "TOTPRegister.OR": "Aŭ",
    "TOTPVerify.ENTER_CODE": "Enigu {length}-ciferan kodon",
    "TOTPVerify.HOW_TO_USE": "Kiel uzi aŭtentigan aplikaĵon.",
    "TOTPVerify.NEXT": "Sekva",
    "TOTPVerify.VERIFY": "Uzu kontrolan kodon el via aŭtentiga aplikaĵo."
});
}