// This file was generated by silverstripe/tx-translator from client/lang/src/fi_FI.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fi_FI', {
    "TOTPRegister.BACK": "Takaisin",
    "TOTPRegister.HOW_TO_USE": "Miten käytät todennus sovellusta.",
    "TOTPRegister.INTRO": "Todennuskoodit luodaan puhelimesi sovelluksella.",
    "TOTPRegister.MANUAL": "Kirjoita seuraava koodi käsin todennus sovellukseen:",
    "TOTPRegister.NEXT": "Seuraava",
    "TOTPRegister.OR": "Tai",
    "TOTPVerify.ENTER_CODE": "Lisää {length}-numeroinen koodi",
    "TOTPVerify.HOW_TO_USE": "Miten käytät todennus sovellusta.",
    "TOTPVerify.NEXT": "Seuraava",
    "TOTPVerify.VERIFY": "Käytä varmennuskoodia todennus sovelluksestasi."
});
}