// This file was generated by silverstripe/tx-translator from client/lang/src/fr.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('fr', {
    "TOTPRegister.BACK": "Retour",
    "TOTPRegister.HOW_TO_USE": "Comment utilise l'application d'authentification.",
    "TOTPRegister.INTRO": "Vérification des codes créés par l'application de votre téléphone.",
    "TOTPRegister.MANUAL": "Saisir manuellement le code suivant dans l'application d'authentification :",
    "TOTPRegister.NEXT": "Suivant",
    "TOTPRegister.OR": "Ou",
    "TOTPVerify.ENTER_CODE": "Saisir code {length}-numérique",
    "TOTPVerify.HOW_TO_USE": "Comment utilise l'application d'authentification.",
    "TOTPVerify.NEXT": "Suivant",
    "TOTPVerify.VERIFY": "Utiliser le code de vérification à partir de votre application d'authentification"
});
}