// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "TOTPRegister.NEXT": "Volgende",
    "TOTPRegister.BACK": "Vorige",
    "TOTPRegister.INTRO": "Verificaties codes worden gegenereerd via een app op je telefoon.",
    "TOTPRegister.OR": "of",
    "TOTPRegister.MANUAL": "Type de code handmatig over in je Authenticator-app",
    "TOTPRegister.HOW_TO_USE": "Hoe gebruik je een authenticator app?",
    "TOTPVerify.NEXT": "Volgende",
    "TOTPVerify.HOW_TO_USE": "Hoe gebruik je een authenticator app?",
    "TOTPVerify.VERIFY": "Gebruik de verificatie-code van je Authenticator-app op je telefoon",
    "TOTPVerify.ENTER_CODE": "Voor een {length}-cijferige code in"
});
}