// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "TOTPRegister.BACK": "Späť",
    "TOTPRegister.HOW_TO_USE": "Ako používať aplikáciu autentifikátora.",
    "TOTPRegister.INTRO": "Overovacie kódy sa vytvárajú pomocou aplikácie v telefóne.",
    "TOTPRegister.MANUAL": "Do aplikácie na overovanie zadajte manuálne nasledujúci kód:",
    "TOTPRegister.NEXT": "Ďalej",
    "TOTPRegister.OR": "Alebo",
    "TOTPVerify.ENTER_CODE": "Zadajte {length}-miestny kód",
    "TOTPVerify.HOW_TO_USE": "Ako používať aplikáciu autentifikátora.",
    "TOTPVerify.NEXT": "Ďalej",
    "TOTPVerify.VERIFY": "Použite overovací kód z aplikácie autentifikátora."
});
}