// This file was generated by silverstripe/tx-translator from client/lang/src/sv.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "TOTPRegister.BACK": "Tillbaka",
    "TOTPRegister.HOW_TO_USE": "Hur man använder autentiseringsappen.",
    "TOTPRegister.INTRO": "Verifieringskoderna skapas av en app på din telefon.",
    "TOTPRegister.MANUAL": "Ange manuellt följande kod i autentiseringsappen:",
    "TOTPRegister.NEXT": "Nästa",
    "TOTPRegister.OR": "Eller",
    "TOTPVerify.ENTER_CODE": "Ange {length}-siffrig kod",
    "TOTPVerify.HOW_TO_USE": "Hur man använder autentiseringsappen.",
    "TOTPVerify.NEXT": "Nästa",
    "TOTPVerify.VERIFY": "Använd verifieringskoden från din autentiseringsapp."
});
}